### ISSUE TITLE
examples are not working anymore with version > 0.2.0

### ISSUE THREAD

**Issue by rommon** [formapro/pvm#16]
Version: 0.2.3

example: https://github.com/formapro/pvm/blob/master/docs/sequence-example.md

```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Makasim\Values\array_set() must be of the type array, null given, called in C:\DEV\workspace\testing\pvmTest\vendor\makasim\values\src\functions\objects.php on line 81 and defined in C:\DEV\workspace\testing\pvmTest\vendor\makasim\values\src\functions\array.php:24
Stack trace:
#0 C:\DEV\workspace\testing\pvmTest\vendor\makasim\values\src\functions\objects.php(81): Makasim\Values\array_set('transitions.0', Object(Formapro\Pvm\TokenTransition), NULL)
#1 [internal function]: Formapro\Pvm\Token->Makasim\Values\{closure}('transitions', Object(Formapro\Pvm\TokenTransition), 0)
#2 C:\DEV\workspace\testing\pvmTest\vendor\makasim\values\src\functions\objects.php(87): Closure->call(Object(Formapro\Pvm\Token), 'transitions', Object(Formapro\Pvm\TokenTransition), NULL)
#3 C:\DEV\workspace\testing\pvmTest\vendor\formapro\pvm\src\Token.php(67): Makasim\Values\add_object(Object(Formapro\Pvm\Token), 'transitions', Object(Formapro\Pvm\TokenTransition))
#4 C:\DEV\workspace\testing\pvmTe in C:\DEV\workspace\testing\pvmTest\vendor\makasim\values\src\functions\array.php on line 24
```

**Comment by makasim** [comment]
Try to call `register_object_hooks()` function.

**Comment by rommon** [comment]
ok, now it works a little bit better. thanks.

But there are still problems. The NullProcessStorage is not correctly implementing the ProcessStorage interface. It is missing the return types and the function getByToken is completly missing.


so these are the steps I did:
1) require the pvm lib
```
composer require formapro/pvm
```
2) simple php file
```php
<?php

use Formapro\Pvm\DefaultBehaviorRegistry;
use Formapro\Pvm\CallbackBehavior;
use Formapro\Pvm\ProcessEngine;
use Formapro\Pvm\Process;
use Formapro\Pvm\Token;
use function Makasim\Values\register_object_hooks;

require "vendor/autoload.php";


register_object_hooks();

$registry = new DefaultBehaviorRegistry();
$registry->register('print_label', new CallbackBehavior(function (Token $token) {
    echo $token->getCurrentTransition()->getTransition()->getTo()->getLabel() . ' ';
}));

$process = Process::create();
$fooNode = $process->createNode();
$fooNode->setLabel('foo');
$fooNode->setBehavior('print_label');

$barNode = $process->createNode();
$barNode->setLabel('bar');
$barNode->setBehavior('print_label');

$process->createTransition($fooNode, $barNode);

$transition = $process->createTransition(null, $fooNode);
$token = $process->createToken($transition);

(new ProcessEngine($registry))->proceed($token);
```

3)
This gives me this:
```
PHP Fatal error:  Declaration of Formapro\Pvm\NullProcessStorage::persist(Formapro\Pvm\Process $process) must be compatible with Formapro\Pvm\ProcessStorage::persist(Formapro\Pvm\Process $process): void in C:\DEV\workspace\testing\pvmTest\vendor\formapro\pvm\src\NullProcessStorage.php on line 4
PHP Stack trace:
PHP   1. {main}() C:\DEV\workspace\testing\pvmTest\pvmTest.php:0
PHP   2. Formapro\Pvm\ProcessEngine->__construct() C:\DEV\workspace\testing\pvmTest\pvmTest.php:34
PHP   3. spl_autoload_call() C:\DEV\workspace\testing\pvmTest\vendor\formapro\pvm\src\ProcessEngine.php:53
PHP   4. Composer\Autoload\ClassLoader->loadClass() C:\DEV\workspace\testing\pvmTest\vendor\formapro\pvm\src\ProcessEngine.php:53
PHP   5. Composer\Autoload\includeFile() C:\DEV\workspace\testing\pvmTest\vendor\composer\ClassLoader.php:322
PHP   6. include() C:\DEV\workspace\testing\pvmTest\vendor\composer\ClassLoader.php:444
```

4)
after updating the NullProcessStorage.php to:
```php
<?php

namespace Formapro\Pvm;

class NullProcessStorage implements ProcessStorage
{
    /**
     * {@inheritdoc}
     */
    public function persist(Process $process): void
    {
    }

    /**
     * {@inheritdoc}
     */
    public function get(string $id): Process
    {
        throw new \LogicException(sprintf('The process with id "%s" could not be found', $id));
    }

    /**
     * {@interhitdoc}
     */
    public function getByToken(string $token): Process
    {
        // TODO: Implement getByToken() method.
    }
}
```
I saw that psr/log is not required
```
PHP Fatal error:  Uncaught Error: Class 'Psr\Log\NullLogger' not found in C:\DEV\workspace\testing\pvmTest\vendor\formapro\pvm\src\ProcessEngine.php:74
Stack trace:
#0 C:\DEV\workspace\testing\pvmTest\pvmTest.php(34): Formapro\Pvm\ProcessEngine->proceed(Object(Formapro\Pvm\Token))
#1 {main}
  thrown in C:\DEV\workspace\testing\pvmTest\vendor\formapro\pvm\src\ProcessEngine.php on line 74
```

5)
after requiring psr/log for my test application I end with the following output.

```
PHP Fatal error:  Uncaught TypeError: Return value of Formapro\Pvm\Process::getId() must be of the type string, null returned in C:\DEV\workspace\testing\pvmTest\vendor\formapro\pvm\src\Process.php:32
Stack trace:
#0 C:\DEV\workspace\testing\pvmTest\vendor\formapro\pvm\src\ProcessEngine.php(79): Formapro\Pvm\Process->getId()
#1 C:\DEV\workspace\testing\pvmTest\pvmTest.php(34): Formapro\Pvm\ProcessEngine->proceed(Object(Formapro\Pvm\Token))
#2 {main}
  thrown in C:\DEV\workspace\testing\pvmTest\vendor\formapro\pvm\src\Process.php on line 32
```

**Comment by makasim** [comment]
Thanks for the very detailed report. I fixed all the issues, tagged 0.2.4. Could you please try it out?

**Comment by rommon** [comment]
thanks for updating your code. yes, it works. Thanks! 

I set the ID for the process and then it works. I also tested the condition example under docs. Great Job!

**Comment by tiandaye** [comment]
Type error: Return value of Formapro\Pvm\Process::getId() must be of the type string, null returned
